{% set name = "domb" %}
{% set version = "2023.11.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/domb-{{ version }}.tar.gz
  sha256: 07534d39a936ec2c31e9711730e403d1f3b5e5b6fc41485f4ba550cf4e6f659d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.9
    - setuptools >=61.0
  run:
    - autograd >=1.6
    - ipykernel >=6.19
    - jupyter >=1.0
    - matplotlib-base >=3.7
    - mkdocstrings >=0.18
    - numpy >=1.25
    - pandas >=1.5
    - pathos >=0.3
    - plotly >=5.15
    - python >=3.9
    - scikit-image >=0.19
    - scikit-learn >=1.0
    - scikit-posthocs >=0.7
    - scipy >=0.12

test:
  imports:
    - domb
  commands:
    - pip list
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/domb
  summary: 'DoMB Tools: Python Toolkit of Department of Molecular Biophysics'
  license: MIT
  license_file: LICENSE
  dev_url: https://github.com/wisstock/DoMB_tools

extra:
  recipe-maintainers:
    - goanpeca
    - wisstock
